# Generated by Django 5.1.7 on 2025-04-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0003_case_compaign_contribution_doctor_donation_tip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Guradian',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='admit_date',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='doctor_detail',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='patient_id_or_medical_proof',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='remarks_description',
        ),
        migrations.AddField(
            model_name='medicallead',
            name='description_documents',
            field=models.FileField(blank=True, null=True, upload_to='descriptions/'),
        ),
        migrations.AddField(
            model_name='medicallead',
            name='patient_id',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='case_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='lead_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='prescription_documents',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
