# Generated by Django 5.1.2 on 2025-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0004_delete_doctor_delete_guradian_delete_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Compaign',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Donation_tip',
        ),
        migrations.DeleteModel(
            name='MedicalLead',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lub',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lud',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
