# Generated by Django 5.1.2 on 2025-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0005_signup_delete_case_delete_compaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='raising_fund_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_purpose', models.CharField(default='General', max_length=255)),
                ('fund_raise_amount', models.IntegerField(default=9999999999)),
                ('fund_title', models.CharField(default='General', unique=True)),
                ('fund_for', models.CharField(default='General', max_length=35, unique=True)),
                ('user_qualification', models.CharField(default='General', max_length=35, unique=True)),
                ('user_emp_status', models.CharField(default='General', max_length=255)),
                ('how_to_know', models.CharField(default='General', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='creation_purpose',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.TextField(default='123456', max_length=35),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile_number',
            field=models.BigIntegerField(default=9999999999, unique=True),
        ),
    ]
