# Generated by Django 5.1.2 on 2025-04-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0006_raising_fund_info_signup_creation_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile_number',
            field=models.BigIntegerField(default=9999999999),
        ),
    ]
