# Generated by Django 5.1.2 on 2025-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0007_alter_signup_email_alter_signup_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raising_fund_info',
            name='fund_raise_amount',
            field=models.IntegerField(default=9999999999, max_length=999999999999999),
        ),
    ]
