# Generated by Django 5.1.2 on 2025-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0008_alter_raising_fund_info_fund_raise_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='raising_fund_for',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_purpose', models.CharField(max_length=255)),
                ('fund_raise_amount', models.IntegerField(max_length=999999999999999)),
                ('fund_title', models.CharField(unique=True)),
                ('fund_for', models.CharField(max_length=35, unique=True)),
                ('user_qualification', models.CharField(max_length=35, unique=True)),
                ('user_emp_status', models.CharField(max_length=255)),
                ('how_to_know', models.CharField(max_length=255)),
            ],
        ),
    ]
