# Generated by Django 5.1.2 on 2025-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0009_raising_fund_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raising_fund_info',
            name='fund_for',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='fund_purpose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='fund_raise_amount',
            field=models.IntegerField(max_length=999999999999999),
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='fund_title',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='how_to_know',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='user_emp_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='user_qualification',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
