# Generated by Django 5.1.2 on 2025-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0010_alter_raising_fund_info_fund_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='creation_purpose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.TextField(max_length=35),
        ),
    ]
