# Generated by Django 5.1.2 on 2025-04-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0011_alter_signup_creation_purpose_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patienet_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paitient_full_name', models.CharField(max_length=255)),
                ('paitient_age', models.IntegerField(max_length=999999999999999)),
                ('hospitalisation_status', models.CharField(unique=True)),
                ('hospital', models.CharField(max_length=35, unique=True)),
                ('enter_city', models.CharField(max_length=35, unique=True)),
                ('user_emp_status', models.CharField(max_length=255)),
                ('how_to_know', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='patienet_story_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patienet_story', models.TextField()),
                ('attachments', models.TextField(default='zxcvbnm')),
            ],
        ),
        migrations.CreateModel(
            name='raising_fund_ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_raising_amount', models.IntegerField(max_length=999999999999999)),
                ('fund_title', models.CharField(unique=True)),
                ('ngo_name', models.CharField(max_length=255)),
                ('user_qualification', models.CharField(max_length=35, unique=True)),
                ('user_emp_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='raising_fund_for',
        ),
        migrations.RenameField(
            model_name='raising_fund_info',
            old_name='fund_raise_amount',
            new_name='fund_raising_amount',
        ),
        migrations.AddField(
            model_name='raising_fund_info',
            name='attachments',
            field=models.TextField(default='zxcvbnm'),
        ),
    ]
