# Generated by Django 5.1.2 on 2025-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0012_patienet_info_patienet_story_info_raising_fund_ngo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund_raising_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField()),
                ('user_id', models.CharField(unique=True)),
                ('user_qualification', models.CharField(max_length=255)),
                ('user_employed_status', models.CharField(max_length=35, unique=True)),
                ('how_to_know', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('fund_title', models.CharField(max_length=255)),
                ('fund_purpose', models.CharField(max_length=255)),
                ('fund_for', models.CharField(max_length=255)),
                ('fund_raising_amount', models.CharField(max_length=255)),
                ('amount_raised', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('ngo_name', models.CharField(max_length=255)),
                ('ngo_registration_number', models.CharField(max_length=255)),
                ('ngo_website_url', models.CharField(max_length=255)),
                ('patienet_full_name', models.CharField(max_length=255)),
                ('patienet_age', models.CharField(max_length=255)),
                ('hospitalization_status', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_location', models.CharField(max_length=255)),
                ('animal_type', models.CharField(max_length=255)),
                ('animal_name', models.CharField(max_length=255)),
                ('animal_age', models.CharField(max_length=255)),
                ('treatment_reason', models.CharField(max_length=255)),
                ('vetnairy_name', models.CharField(max_length=255)),
                ('vetnairy_clinic_name', models.CharField(max_length=255)),
                ('attachments', models.CharField(max_length=255)),
                ('medical_documents', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('created_date', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('last_created_date', models.CharField(max_length=255)),
                ('last_created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='raising_fund_ngo',
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='attachments',
            field=models.TextField(),
        ),
    ]
