# Generated by Django 5.1.2 on 2025-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0013_fund_raising_form_delete_raising_fund_ngo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_raising_form',
            name='amount_raised',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='animal_age',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='attachments',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='created_date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='end_date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='fund_raising_amount',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='last_created_date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='medical_documents',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='patienet_age',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='start_date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
