# Generated by Django 5.1.2 on 2025-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0014_alter_fund_raising_form_amount_raised_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_raising_form',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='user_info',
            field=models.CharField(max_length=255),
        ),
    ]
