# Generated by Django 5.1.2 on 2025-04-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0015_alter_fund_raising_form_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_raising_form',
            name='amount_raised',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='animal_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='animal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='animal_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='fund_for',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='fund_purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='fund_raising_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='fund_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='hospital_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='hospitalization_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='how_to_know',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='last_created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='medical_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='ngo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='ngo_registration_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='ngo_website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='patienet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='patienet_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='treatment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='user_employed_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='user_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='user_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='vetnairy_clinic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='vetnairy_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
