# Generated by Django 5.1.2 on 2025-04-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0016_alter_fund_raising_form_amount_raised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_raising_form',
            name='patienet_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
