# Generated by Django 5.1.2 on 2025-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0017_fund_raising_form_patienet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_raising_form',
            name='last_created_date',
            field=models.DateField(null=True),
        ),
    ]
