# Generated by Django 5.1.2 on 2025-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0018_alter_fund_raising_form_last_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_raising_form',
            name='patienet_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
