# Generated by Django 5.1.7 on 2025-07-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0019_alter_fund_raising_form_patienet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_generate_by', models.CharField(max_length=255)),
                ('lead_purpose', models.TextField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_address', models.TextField()),
                ('patient_age', models.IntegerField()),
                ('patient_case', models.TextField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_date', models.DateField()),
                ('patient_education', models.CharField(max_length=255)),
                ('patient_occupation', models.CharField(max_length=255)),
                ('patient_pic_2', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('patient_id', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_number', models.CharField(max_length=15)),
                ('hospital_name', models.CharField(max_length=255)),
                ('doctor_number', models.CharField(max_length=15)),
                ('prescription_documents', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('description_documents', models.FileField(blank=True, null=True, upload_to='descriptions/')),
                ('case_type', models.CharField(max_length=100)),
                ('lead_source', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paitient_full_name', models.CharField(max_length=255)),
                ('paitient_age', models.IntegerField()),
                ('hospitalisation_status', models.CharField(unique=True)),
                ('hospital', models.CharField(max_length=35, unique=True)),
                ('enter_city', models.CharField(max_length=35, unique=True)),
                ('user_emp_status', models.CharField(max_length=255)),
                ('how_to_know', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='patienet_story_info',
            new_name='patient_story_info',
        ),
        migrations.DeleteModel(
            name='patienet_info',
        ),
        migrations.AlterField(
            model_name='raising_fund_info',
            name='fund_raising_amount',
            field=models.IntegerField(),
        ),
    ]
