# Generated by Django 5.1.7 on 2025-12-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0020_medicallead_patient_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('case_type', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('parties_detail', models.TextField()),
                ('published_source', models.CharField(blank=True, max_length=255, null=True)),
                ('case_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('contributor_name', models.CharField(max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_status', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation_tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, help_text='GST percentage applied to the transaction', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Fee charged by the platform', max_digits=12)),
                ('tips', models.DecimalField(blank=True, decimal_places=2, help_text='Optional tip amount', max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default_user', max_length=150)),
                ('password', models.CharField(default='changeme123', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties_name', models.CharField(max_length=255)),
                ('parties_email', models.EmailField(max_length=254, unique=True)),
                ('parties_number', models.CharField(max_length=15)),
                ('parties_social_media_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='patient_page_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_full_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField(default=0)),
                ('hospitalisation_status', models.CharField(unique=True)),
                ('hospital', models.CharField(max_length=35, unique=True)),
                ('enter_city', models.CharField(max_length=35, unique=True)),
                ('user_emp_status', models.CharField(max_length=255)),
                ('how_to_know', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField(blank=True, null=True)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='patient_info',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='description_documents',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='medicallead',
            name='admit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicallead',
            name='doctor_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicallead',
            name='patient_id_or_medical_proof',
            field=models.FileField(blank=True, null=True, upload_to='medical_proofs/'),
        ),
        migrations.AddField(
            model_name='medicallead',
            name='remarks_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raising_form',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='case_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='doctor_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='estimate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='estimate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='guardian_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='lead_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='lead_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='patient_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='patient_case',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='patient_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='patient_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicallead',
            name='prescription_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediFundapp.user'),
        ),
    ]
