# Generated by Django 5.1.7 on 2025-12-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0021_case_compaign_contribution_donation_tip_login_party_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
